- name: demo loops
  hosts: localhost
  tasks:
    - name: loop demo
      ansible.builtin.debug:
        msg: hello, "{{ item.name }}", age of yours is "{{ item.age }}" years.
      loop:
        - { name: "nare" , age: 20}
        - { name: "ram" , age: 30}
        - { name: "siva" , age: 40}