- name: demo on condition
  hosts: localhost
  tasks:
    - name: say hii to john
      ansible.builtin.debug:
        msg: hey, john

    - name: say hello to ram
      ansible.builtin.debug:
        msg: hey,ram