- name: demo handlers
  hosts: localhost
  tasks:
    - name: copy sample
      ansible.builtin.template:
        src: sample.txt
        dest: /tmp/sample.txt
      notify: say hello

  handlers:
        - name: say hello
          ansible.builtin.debug:
            msg: hello {{ name }} again !!
