- name: demo ignore
  hosts: localhost
  tasks:
    - name: run shell command
      ansible.builtin.shell: exit 1
      ignore: yes

    - name: say hii
      ansible.builtin.debug:
        msg: hai

