- name: demo rescue
  host: localhost
  tasks:
    - name: block
      block:
        - name: run shell command
          ansible.builtin.shell: exit 1
          ignore_errors: yes

      rescue:
        - name: hey hello
          ansible.builtin.debug:
            msg: hii
