- name: demo rescue
  hosts: localhost
  tasks:
    - name: block
      block:
        - name: run shell command
          ansible.builtin.shell: exit 1


      rescue:
        - name: hey hello
          ansible.builtin.debug:
            msg: hii
