- name: demo rescue
  hosts: localhost
  tasks:
    - name: block
      block:
        - name: run shell command
          ansible.builtin.shell: exit 1
          ignore_errors: yes
      rescue:
        - name: say hii
          ansible.builtin.debug:
            msg: hai

