- name: demo on vars
  hosts: localhost
  vars:
    url: play.google.com
  tasks:
    - name: print play level variable
      ansible.builtin.debug:
        msg: url = {{ url }}

    - name: print variable declere the tasks
      vars:
        url: task.google.com
      ansible.builtin.debug:
        msg: url = {{ url }}

  roles:
    - demo
